spring.application.name=FullStackRevConnect

server.port=8080

# DATABASE (Docker container name = mariadb-db)
spring.datasource.url=jdbc:mariadb://mariadb-db:3306/full_stack_rev_connect
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

# JWT
app.jwt.secret=ThisIsSuperSecureSecretKeyForJWTMustBeVeryLong123456789
app.jwt.expiration=86400000

logging.level.org.springframework.security=DEBUG

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true